#!/bin/bash -
source config

for f in "${HOME}/.vimrc" "${VIM_DIR}"; do
  [ -e "$f" ] && mv -f "$f" "${f}.${BACKUP_SUFFIX}";
done

vim -u "${VIMRC_BUNDLES_CONF}" -i NONE -V1 -nNes +PlugClean! +PlugInstall +PlugUpdate +qall!
