#!/bin/bash -
set -x

cd "$(dirname "$0")"

source config


# Backup existing configuration
[ -e "~/.vimrc" ] && mv -f "~/.vimrc" "~/.vimrc.${BACKUP_SUFFIX}";
if [ -d "${VIM_DIR}" ]; then
  tar -C "$(dirname "${VIM_DIR}")" czf "${VIM_DIR}.${BACKUP_SUFFIX}.tar.gz" "${VIM_DIR}" && \
    rm -rf "${VIM_DIR}"
fi

# Download vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Copy new configuration files
mkdir ~/.vim
cp -R vimrc conf.d ~/.vim

# Launch plugin installation
vim -i NONE -V1 -nNe -S ./install.vim
